//
// CategoryExplore.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class CategoryExplore: Codable {

    public var description: String?
    public var favorite: Bool?
    public var iconUrl: String?
    public var id: Int64?
    public var name: String?


    
    public init(description: String?, favorite: Bool?, iconUrl: String?, id: Int64?, name: String?) {
        self.description = description
        self.favorite = favorite
        self.iconUrl = iconUrl
        self.id = id
        self.name = name
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(description, forKey: "description")
        try container.encodeIfPresent(favorite, forKey: "favorite")
        try container.encodeIfPresent(iconUrl, forKey: "iconUrl")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(name, forKey: "name")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        description = try container.decodeIfPresent(String.self, forKey: "description")
        favorite = try container.decodeIfPresent(Bool.self, forKey: "favorite")
        iconUrl = try container.decodeIfPresent(String.self, forKey: "iconUrl")
        id = try container.decodeIfPresent(Int64.self, forKey: "id")
        name = try container.decodeIfPresent(String.self, forKey: "name")
    }
}

