//
// GetBusinessType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class GetBusinessType: Codable {

    public var businessType: Int?


    
    public init(businessType: Int?) {
        self.businessType = businessType
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(businessType, forKey: "business_type")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        businessType = try container.decodeIfPresent(Int.self, forKey: "business_type")
    }
}

