//
// SettingResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SettingResponse: Codable {

    public var alert: AlertSetting?
    public var general: GeneralSetting?


    
    public init(alert: AlertSetting?, general: GeneralSetting?) {
        self.alert = alert
        self.general = general
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(alert, forKey: "alert")
        try container.encodeIfPresent(general, forKey: "general")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        alert = try container.decodeIfPresent(AlertSetting.self, forKey: "alert")
        general = try container.decodeIfPresent(GeneralSetting.self, forKey: "general")
    }
}

