//
// CategoryControllerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire
import RxSwift



open class CategoryControllerAPI {
    /**
     getCategoriesWithIcon
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getCategoriesWithIconUsingGET(completion: @escaping ((_ data: [CategoryExplore]?,_ error: Error?) -> Void)) {
        getCategoriesWithIconUsingGETWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }

    /**
     getCategoriesWithIcon
     
     - returns: Observable<[CategoryExplore]>
     */
    open class func getCategoriesWithIconUsingGET() -> Observable<[CategoryExplore]> {
        return Observable.create { observer -> Disposable in
            getCategoriesWithIconUsingGET() { data, error in
                if let error = error {
                    observer.on(.error(error))
                } else {
                    observer.on(.next(data!))
                }
                observer.on(.completed)
            }
            return Disposables.create()
        }
    }

    /**
     getCategoriesWithIcon
     - GET /category/withIcon
     - API Key:
       - type: apiKey user-token 
       - name: usertoken
     - examples: [{output=none}]

     - returns: RequestBuilder<[CategoryExplore]> 
     */
    open class func getCategoriesWithIconUsingGETWithRequestBuilder() -> RequestBuilder<[CategoryExplore]> {
        let path = "/category/withIcon"
        let URLString = JAPIv2ClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[CategoryExplore]>.Type = JAPIv2ClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
